Add Originator and Timestamp columns
LimeChain/hashport-validator pull request #612
Opened 2022-05-10 15:19 UTC by vectorman1

**Detailed description**:

**Which issue(s) this PR fixes**:
Fixes #597

**Special notes for your reviewer**:

**Checklist**
- [ ] Documentation added
- [ ] Tests updated

2022-05-10 15:50 UTC, failfmi commented on app/process/watcher/evm/watcher.go
> +		ew.logger.Errorf("[%s] - Failed to get originator. Error: [%s]", eventLog.Raw.TxHash, err)
nit: missing return

2022-05-10 15:50 UTC, failfmi commented on app/process/watcher/evm/watcher.go
> +		ew.logger.Errorf("[%s] - Failed to get originator. Error: [%s]", eventLog.Raw.TxHash, err)
nit: missing return

2022-05-10 15:50 UTC, failfmi commented on app/process/watcher/evm/watcher.go
> +		ew.logger.Errorf("[%s] - Failed to get originator. Error: [%s]", eventLog.Raw.TxHash, err)
nit: missing return

2022-05-10 15:50 UTC, failfmi commented on app/helper/evm/helper.go
> +	msg, err := tx.AsMessage(types.NewEIP155Signer(tx.ChainId()), nil)
https://github.com/ethereum/go-ethereum/issues/23890#issuecomment-966794849

2022-05-12 07:53 UTC, svetlio8 submitted a review, later dismissed

2022-05-12 09:30 UTC, Psykepro submitted a review, later dismissed

2022-05-13 06:19 UTC, failfmi requested changes
In the end of each `E2E`, we assert whether the DB has the correct values set for each transfer. Could we add checks for the timestamp & originator?

2022-05-13 06:19 UTC, failfmi commented on test/mocks/repository/transfer_repository_mock.go
> +}
Are these needed for this PR?

2022-05-13 06:19 UTC, failfmi commented on config/node.go
> +	PollingInterval time.Duration `yaml:"polling_interval"`
Instead of changing this, could you use `parser/node.go > MirrorNode`

2022-05-13 06:19 UTC, failfmi commented on scripts/migration/add_timestamp_and_originator_to_transfers/main.go
> +	log.Infof("finna update %d nodes using %d evm clients", len(migrator.nodes), len(migrator.evmClients))
nit: let's switch `finna` to something more understandable

2022-05-13 06:47 UTC, failfmi requested changes
Could we add a small documentation regarding the migration script? At least to explain the config

2022-05-13 06:47 UTC, failfmi commented on scripts/migration/add_timestamp_and_originator_to_transfers/main.go
> +	PrivateKey string                  `yaml:"private_key"`
These are not used

2022-05-13 06:47 UTC, failfmi commented on scripts/migration/add_timestamp_and_originator_to_transfers/main.go
> +	DBs    []validatorCfg.Database `yaml:"dbs"`
`parser/node.go` > `Database`

2022-05-13 06:57 UTC, failfmi commented
One error when running the migration on db with records that already have a set timestamp:
`sql: Scan error on column index 2, name "timestamp": unsupported Scan, storing driver.Value type int64 into type *time.Time `

2022-05-13 07:01 UTC, failfmi commented on scripts/migration/add_timestamp_and_originator_to_transfers/main.go
> +			err := m.fillTimestampAndOriginator(t)
Can we add logs for each transfer that we update - tx id, and the to-be-set originator & timestamp?

2022-05-13 07:44 UTC, failfmi commented on scripts/migration/add_timestamp_and_originator_to_transfers/main.go
> +			err := m.fillTimestampAndOriginator(t)
Plus the DB we update it to as well

2022-05-13 08:23 UTC, vectorman1 commented on app/helper/evm/helper.go
> +	return msg.From().String(), nil
Adding ToLower

2022-05-16 07:33 UTC, failfmi approved these changes
LGTM

2022-05-16 08:58 UTC, Psykepro approved these changes

2022-05-16 08:58 UTC, merged