Add /fees/nft endpoint
LimeChain/hashport-validator pull request #639
Opened 2022-06-08 11:18 UTC by vectorman1

Signed-off-by: Boris Lachev <boris.lachev@icloud.com>

**Detailed description**:

**Which issue(s) this PR fixes**:
Fixes #621 

**Special notes for your reviewer**:

**Checklist**
- [x] Documentation added
- [x] Tests updated

2022-06-08 11:51 UTC, svetlio8 commented on app/router/fees/fees.go
> +package fees
Missing license

2022-06-08 13:44 UTC, svetlio8 approved these changes

2022-06-09 05:52 UTC, failfmi commented on app/services/pricing/service.go
> +	}
You call this in `instance.FetchAndUpdateUsdPrices()`, is there any point this to still be called here?

2022-06-09 05:57 UTC, failfmi commented on app/services/pricing/service_test.go
> +	client2 "github.com/limechain/hedera-eth-bridge-validator/app/domain/client"
Can we rename this to something more meaningful?

2022-06-09 06:11 UTC, failfmi commented on app/services/pricing/service.go
> +func (s *Service) FetchAndUpdateNftFeesForApi() error {
nit: we can lower the visibility of this function

2022-06-09 13:05 UTC, failfmi requested changes

2022-06-09 13:05 UTC, failfmi commented on app/domain/service/pricing.go
> +	fetchAndUpdateNftFeesForApi() error
I guess this is no longer needed.

2022-06-09 13:47 UTC, failfmi approved these changes

2022-06-09 14:37 UTC, merged