651 Support for NFT with royalty fees
LimeChain/hashport-validator pull request #658
Opened 2022-06-29 08:02 UTC by vectorman1

**Detailed description**:

**Which issue(s) this PR fixes**:
Fixes #651

**Special notes for your reviewer**:

**Checklist**
- [x] Documentation added
- [x] Tests updated

2022-06-29 08:07 UTC, failfmi commented
Pull from `main` to get the latest diagrams for the flows.
Docs in https://github.com/LimeChain/hashport-validator/blob/main/docs/overview.md
https://github.com/LimeChain/hashport-validator/blob/main/docs/integration.md
have to be updated as well.

2022-07-04 06:30 UTC, failfmi commented on app/services/read-only/service.go
> +		txs, err := s.mirrorNode.GetTransactionsAfterTimestamp(sender, t.Timestamp.UnixNano(), ScheduleCreate)
I think that here you will need to fetch `CryptoApproveAllowance` transactions.

2022-07-04 06:32 UTC, failfmi commented on e2e/e2e_test.go
> +	validateNftSpender(t, setupEnv, nftToken, serialNumber, setupEnv.BridgeAccount)
I think that here the owner is still the the bridge account.

2022-07-04 06:34 UTC, failfmi commented on e2e/e2e_test.go
> +		scheduleCreates, err := setupEnv.Clients.MirrorNode.GetTransactionsAfterTimestamp(setupEnv.BridgeAccount, startTimestamp, read_only.ScheduleCreate)
read_only.CryptoApprovaAllowance

2022-07-04 06:36 UTC, failfmi commented on e2e/e2e_test.go
Last but not least, the user (e2e test) has to execute the crypto transfer transaction and take the nft to its account. The idea is e2e tests to be circular - previous test wraps the NFT, this one unlocks/unwraps it.

2022-07-04 06:36 UTC, failfmi requested changes
.

2022-07-18 10:05 UTC, failfmi requested changes

2022-07-18 10:05 UTC, failfmi commented on docs/integration.md
> +After the burn transaction has been mined, the NFT is approved for the user. Then, the user can submit a transfer transaction on Hedera to get it back.
An example of what Hedera transaction to execute using the SDK is missing.

2022-07-18 10:05 UTC, failfmi commented
Tests are failing

2022-07-20 08:06 UTC, Psykepro approved these changes

2022-07-20 08:22 UTC, svetlio8 approved these changes

2022-07-21 14:48 UTC, merged