650 - Feature/nft with royalty h to evm
LimeChain/hashport-validator pull request #659
Opened 2022-06-29 09:15 UTC by Psykepro

**Detailed description**:

**Which issue(s) this PR fixes**:
Fixes #650

**Special notes for your reviewer**:

**Checklist**
- [x] Documentation added
- [x] Tests updated

2022-07-01 05:03 UTC, vectorman1 commented on app/clients/hedera/client.go
> +	transferTransaction := hedera.NewTransferTransaction().AddApprovedNftTransfer(nftID, sender, receiving, approved)
nit: break line

2022-07-04 05:50 UTC, failfmi commented on app/helper/hedera/nft.go
> +			defer wg.Done()
Why this is here?

2022-07-04 06:07 UTC, failfmi requested changes
Have you tested the flow with an NFT that has fixed fee?

There is an empty bridge.yml file in `scripts/bridge/bridge.yml` that has to be removed.

2022-07-04 06:07 UTC, failfmi commented on docs/overview.md
> +   **1.1** Alice sends `Allowance` for the NFT to the `Payer Account` of the `Bridge`
Alice executes `CryptoApproveAllowance` transaction for the given NFT, specifying the spender to be `Payer Account` of the bridge configuration.

2022-07-04 06:07 UTC, failfmi commented on docs/overview.md
> +   **1.2** Alice wants to transfer `HTS NFT` from Hedera to the EVM chain. She opens any UI that integrates the Bridge and sends the flat fee and all the necessary Royalty (fallback fee) and Fixed fe
`Alice wants to transfer HTS NFT from Hedera to the EVM chain. She opens any UI that integrates the Bridge` - this has to be before 1.1.

2022-07-04 06:07 UTC, failfmi commented on docs/overview.md
> +   **3.1** Each of the Validators create a Schedule Create transaction transferring the `NFT` to the `Bridge` account.
Each of the Validators create a Schedule Create transaction, which transfers the `NFT` to the `Bridge` account.

2022-07-04 06:07 UTC, failfmi commented on docs/overview.md
> +6. **Paying out fees**
This has to be `4.`

2022-07-04 06:07 UTC, failfmi commented on docs/overview.md
> +7. **Providing Authorisation Signature**
5.

2022-07-04 06:07 UTC, failfmi commented on docs/overview.md
> +8. **Waiting for Supermajority**
6.

2022-07-04 06:07 UTC, failfmi commented on docs/overview.md
> +9. **Submitting the EVM Transaction**
7.

2022-07-04 06:07 UTC, failfmi commented on docs/overview.md
> +    The smart contract verifies that no reply attack is being executed by verifying the provided signatures against the raw data that was signed. If supermajority is reached, the `Router` contract `m
8.

2022-07-04 06:20 UTC, failfmi commented on app/process/watcher/transfer/watcher.go
> +		ctw.initSuccessRatePrometheusMetrics(tx, constants.HederaNetworkId, targetChainId, sourceAsset)
Isn't this reversed now?

2022-07-04 06:25 UTC, failfmi requested changes
There is one more documentation file that has to be updated: `integration.md`.

There you have to explain which transactions are executed by users, with which values being sent (fallback fees, hbar fee, etc.)

2022-07-04 10:16 UTC, Psykepro commented
> 

Tested it with FixedFee now and it works.

2022-07-04 14:24 UTC, Psykepro commented
> > @failfmi
> 
> Tested it with FixedFee now and it works.

Actually, when the Fee is FixedFee it is deducted from the owner's account so we don't need to expect from the User to send us that amount. Will fix it now.

2022-07-05 06:16 UTC, failfmi commented on app/helper/hedera/nft.go
> +			logger.Errorf(
I think that the status result should still be set to FAIL.

2022-07-05 06:19 UTC, failfmi commented on app/helper/hedera/nft.go
> +			logger.Errorf(
If it is not set to FAIL, upon mined, it will try to update something that has not been created.

2022-07-05 06:20 UTC, failfmi commented on app/helper/fee/fee.go
> +}
Do you think this is needed?

2022-07-05 06:26 UTC, failfmi commented on docs/integration.md
>      AddNftTransfer(nftID, client.GetOperatorAccountID(), bridgeAccount). // Send the NFT to the bridge account
You do not need this anymore.

2022-07-05 06:27 UTC, failfmi commented on docs/integration.md
> +    ).Execute(setup.Clients.Hedera)
`setup.Clients.Hedera` -> `client`

2022-07-05 06:29 UTC, failfmi commented on docs/integration.md
> +        ownerAccountId, // The user's account ID
`ownerAccountId` -> `client.OperatorAccountID()`

2022-07-05 06:30 UTC, failfmi commented on docs/integration.md
> +        spenderAccountId, // Payer's Account ID from the Bridge Config
`spenderAccountId` -> `payerAccountID`

2022-07-05 06:30 UTC, failfmi commented on docs/integration.md
> +        nftId,
nftID

2022-07-08 14:26 UTC, svetlio8 commented on app/helper/hedera/nft.go
> +/*
missing unit tests

2022-07-08 14:44 UTC, svetlio8 commented on app/process/watcher/transfer/watcher_test.go
>  import (
missing tests for `validateNftTokenCustomFees`

2022-07-11 14:46 UTC, svetlio8 reviewed
Looks like there is an issue with `app/services/assets/assets_test.go` > `Test_New` > 
`assert.Equal(t, serviceInstance.nonFungibleAssetInfos, actualService.nonFungibleAssetInfos)` . Could you please fix it?

2022-07-13 09:59 UTC, failfmi approved these changes
LGTM

2022-07-13 11:00 UTC, svetlio8 approved these changes

2022-07-14 07:00 UTC, merged