Adding implementation for Hedera ID Change backwards compatibility.
LimeChain/hashport-validator pull request #666
Opened 2022-07-07 12:28 UTC by Psykepro

Signed-off-by: Nikolay Nedkov <nikolay.nedkov@limechain.tech>

**Detailed description**:

**Which issue(s) this PR fixes**:
Fixes #633

**Special notes for your reviewer**:

**Checklist**
- [ ] Documentation added
- [x] Tests updated

2022-07-08 13:58 UTC, svetlio8 commented on config/bridge.yml
> -# This file contains application defaults
commit with the cofig

2022-07-08 13:58 UTC, svetlio8 commented on config/node.yml
> +#DAVE read-only
commit with the cofig

2022-07-08 13:58 UTC, svetlio8 commented on e2e/setup/application.yml
>  #E2E ETH-Hedera
commit with the cofig

2022-07-08 13:59 UTC, svetlio8 commented on e2e/setup/bridge.yml
>  # This file contains application defaults
commit with the cofig

2022-07-08 13:59 UTC, svetlio8 commented on examples/three-validators/alice/config/node.yml
>  # This file contains application defaults
commit with the cofig

2022-07-08 13:59 UTC, svetlio8 commented on examples/three-validators/bob/config/node.yml
>  # This file contains application defaults
commit with the cofig

2022-07-08 13:59 UTC, svetlio8 commented on examples/three-validators/bridge.yml
> -#bridge:
commit with the cofig

2022-07-08 13:59 UTC, svetlio8 commented on examples/three-validators/carol/config/node.yml
> -#node:
commit with the cofig

2022-07-08 14:00 UTC, svetlio8 requested changes
Please remove the committed configs

2022-07-11 08:26 UTC, failfmi commented
You have not merged `main` properly. Things that have been committed in main show as changes..

2022-07-11 09:34 UTC, svetlio8 approved these changes
nit: please check e2e

2022-07-13 07:57 UTC, vectorman1 approved these changes

2022-07-13 11:35 UTC, merged