Adding script for extending bridge config for automated bridge setup/…
LimeChain/hashport-validator pull request #686
Opened 2022-08-04 14:12 UTC by Psykepro

…deploy.

Signed-off-by: Nikolay Nedkov <nikolay.nedkov@limechain.tech>

**Detailed description**:

**Which issue(s) this PR fixes**:
Fixes #674

**Special notes for your reviewer**:

**Checklist**
- [x] Documentation added
- [ ] Tests updated

2022-08-04 14:48 UTC, svetlio8 commented on scripts/bridge/setup/extend-config/cmd/extend-bridge-config.go
> +	parser "github.com/limechain/hedera-eth-bridge-validator/scripts/bridge/setup/parser"
nit alias `parse` -> `/parse`

2022-08-05 06:11 UTC, svetlio8 submitted a review, later dismissed

2022-08-05 12:52 UTC, svetlio8 approved these changes

2022-08-05 16:02 UTC, vectorman1 requested changes

2022-08-05 16:02 UTC, vectorman1 commented on scripts/bridge/setup/extend-config/cmd/extend-bridge-config.go
> +	return err
nit: `err` here is `nil`, just return `nil`

2022-08-05 16:02 UTC, vectorman1 commented on scripts/bridge/setup/extend-config/cmd/extend-bridge-config.go
> +	return err
nit: `err` here is `nil`, just return `nil`

2022-08-05 16:02 UTC, vectorman1 commented on app/services/assets/assets.go
> +		a.logger.Errorf("Hedera Mirror Node method GetToken for Asset [%s] - Error: [%s]", assetId, err)
+ `return nil, err`

2022-08-05 16:02 UTC, vectorman1 commented on app/services/assets/assets.go
>  	} else {
else is not necessary

2022-08-05 16:02 UTC, vectorman1 commented on app/services/assets/assets.go
>  	return assetInfo, err
nit: `return assetInfo, nil`

2022-08-09 08:10 UTC, vectorman1 approved these changes

2022-08-09 08:28 UTC, merged