Adding gcp logging driver to docker-compose.yml
LimeChain/hashport-validator pull request #693
Opened 2022-08-11 12:01 UTC by Psykepro

Signed-off-by: Nikolay Nedkov <nikolay.nedkov@limechain.tech>

**Detailed description**:

**Which issue(s) this PR fixes**:
Fixes #647

**Special notes for your reviewer**:

**Checklist**
- [ ] Documentation added
- [ ] Tests updated

2022-08-11 12:43 UTC, svetlio8 submitted a review, later dismissed

2022-08-11 12:44 UTC, rokn approved these changes

2022-08-13 15:14 UTC, svetlio8 approved these changes
Please check and fix for build, unit-tests & e2e

2022-08-13 15:15 UTC, svetlio8 requested changes
Please check and fix for build, unit-tests & e2e

2022-08-16 06:20 UTC, svetlio8 approved these changes

2022-08-18 10:42 UTC, rokn approved these changes

2022-08-19 09:30 UTC, merged