Fix merge conflicts with e2e_refactor
LimeChain/hashport-validator pull request #797
Opened 2022-12-09 20:24 UTC by trayanm

**Detailed description**:
Fixed conflicts issues between branches `main`, `e2e_refactoring` and functionalities for `NFT` & `Fee Per User`.

**Which issue(s) this PR fixes**:
Fixes #773 #618 

**Special notes for your reviewer**:

**Checklist**
- [ ] Documentation added
- [x] Tests updated

2022-12-14 08:57 UTC, rokn commented on e2e/setup/application.yml
> -#E2E ETH-Hedera
This file shouldn't be commited

2022-12-14 19:17 UTC, trayanm commented on e2e/helper/verify/db.go
> +	retryAttempts := 6
I would like to have the option in the config. Unfortunately - part of the essence in `e2e_refactoring` branch is to not use the global config. but passing its values as parameters. 
If we agree of this change - we have to make the same change for some of the API requests, where there is retry mechanism.
My recommendation is to leave the logic like that.

2022-12-14 19:22 UTC, trayanm commented on e2e/helper/verify/db.go
> +	return result, err
The purpose of the retry logic here is to not change the outer logic, where the result of `getScheduleByTransactionId `is handled as is.
I agree that having more logs is always good idea..
I would recommend to spend some more time to apply your suggestion plus other that will come

2022-12-15 07:54 UTC, trayanm commented on e2e/helper/verify/api.go
> +	bytes, err := validatorClient.GetTransferData(txId)
Could you confirm the conditions for retry?
For a web request we should be more careful. Status 404 could still be valid result. My suggestion is the handle only 404 at maximum of 3 retries.

2022-12-15 08:24 UTC, rokn commented on e2e/helper/verify/db.go
> +	retryAttempts := 6
Okay then can we increase the attempts to something bigger 10-15?

2022-12-15 08:27 UTC, rokn commented on e2e/helper/verify/api.go
> +	bytes, err := validatorClient.GetTransferData(txId)
Nope, here the problem is the request is not 404. It's a success(200) but the signatures field is nil/not full. We could imitate the logic in the API flows and wait for `majority: true` or we can wait for all of the signatures(`expectedValidatorCount`)

2022-12-15 09:01 UTC, svetlio8 commented on e2e/helper/expected/db.go
> +func NonFungibleTransferRecord(
Are we using this method?

2022-12-15 09:03 UTC, svetlio8 commented on e2e/e2e_test.go
>  	// 8. Wait for validators to update DB state after Scheduled TX is mined
I think that this comment is not useful anymore

2022-12-15 09:04 UTC, svetlio8 commented on e2e/e2e_test.go
>  	// 8. Wait for validators to update DB state after Scheduled TX is mined
I think that this comment is not useful anymore

2022-12-15 09:04 UTC, svetlio8 commented on e2e/e2e_test.go
>  	// 10. Wait for validators to update DB state after Scheduled TX is mined
I think that this comment is not useful anymore

2022-12-15 09:15 UTC, svetlio8 commented on e2e/e2e_test.go
>  	amount := int64(1000000000) // 10 HBAR
Maybe we can move this number in a constant in a separate file?

2022-12-15 12:21 UTC, svetlio8 commented on e2e/e2e_test.go
>  	amount := int64(1000000000) // 10 HBAR
Maybe we can move this number in a constant in a separate file?

2022-12-15 12:21 UTC, svetlio8 commented on e2e/e2e_test.go
>  	amount := int64(100000000) // 1 HBAR
Maybe we can move this number in a constant in a separate file?

2022-12-15 12:22 UTC, svetlio8 commented on e2e/e2e_test.go
>  	amount := int64(1000000000000) // 1 000 gwei
Maybe we can move this number in a constant in a separate file?

2022-12-15 12:22 UTC, svetlio8 commented on e2e/e2e_test.go
>  	unlockAmount := int64(10) // Amount, which converted to 18 decimals is 100000000000 (100 gwei)
Maybe we can move this number in a constant in a separate file?

2022-12-15 12:22 UTC, svetlio8 commented on e2e/e2e_test.go
>  	amount := int64(1000000000000) // 1000 gwei
Maybe we can move this number in a constant in a separate file?

2022-12-15 12:22 UTC, svetlio8 commented on e2e/e2e_test.go
>  	amount := int64(100000000000) // 100 gwei
Maybe we can move this number in a constant in a separate file?

2022-12-15 12:25 UTC, svetlio8 commented on e2e/e2e_test.go
> +
If we do not have added value from this comment, could we remove it?

2022-12-15 12:25 UTC, svetlio8 commented on e2e/e2e_test.go
> +	// fee := amount * (feeData.ServiceFeePercentage.Int64() / constants.FeeMaxPercentage)
If we do not have added value from this comment, could we remove it?

2022-12-15 12:27 UTC, svetlio8 commented on e2e/e2e_test.go
> -	time.Sleep(20 * time.Second)
I think we will need a more stable fix, as we already sync we could have a re-try in case of timeout.

2022-12-15 12:27 UTC, svetlio8 commented on e2e/e2e_test.go
> -	time.Sleep(20 * time.Second)
I think we will need a more stable fix, as we already sync we could have a re-try in case of timeout.

2022-12-15 12:27 UTC, svetlio8 commented on e2e/e2e_test.go
> -	time.Sleep(30 * time.Second)
I think we will need a more stable fix, as we already sync we could have a re-try in case of timeout.

2022-12-15 12:28 UTC, svetlio8 commented on e2e/e2e_test.go
> -	time.Sleep(30 * time.Second)
I think we will need a more stable fix, as we already sync we could have a re-try in case of timeout.

2022-12-15 12:28 UTC, svetlio8 commented on e2e/e2e_test.go
> -	time.Sleep(30 * time.Second)
I think we will need a more stable fix, as we already sync we could have a re-try in case of timeout.

2022-12-15 12:28 UTC, svetlio8 commented on e2e/e2e_test.go
> -	time.Sleep(30 * time.Second)
I think we will need a more stable fix, as we already sync we could have a re-try in case of timeout.

2022-12-15 12:28 UTC, svetlio8 commented on e2e/e2e_test.go
> -	time.Sleep(30 * time.Second)
I think we will need a more stable fix, as we already sync we could have a re-try in case of timeout.

2022-12-15 12:29 UTC, svetlio8 commented on e2e/e2e_test.go
> -	time.Sleep(30 * time.Second)
I think we will need a more stable fix, as we already sync we could have a re-try in case of timeout.

2022-12-15 12:31 UTC, svetlio8 commented on e2e/e2e_test.go
>  	// 8. Wait for validators to update DB state after Scheduled TX is mined
I think that this comment is not useful anymore

2022-12-15 12:31 UTC, svetlio8 commented on e2e/e2e_test.go
>  	// Wait for validators to update DB state after Scheduled TX is mined
I think that this comment is not useful anymore

2022-12-15 12:51 UTC, svetlio8 commented on e2e/e2e_test.go
>  	// Wait for validators to update DB state after Scheduled TX is mined
I think that this comment is not useful anymore

2022-12-15 12:51 UTC, svetlio8 commented on e2e/e2e_test.go
> -	time.Sleep(30 * time.Second)
I think we will need a more stable fix, as we already sync we could have a re-try in case of timeout.

2022-12-15 14:47 UTC, svetlio8 commented on e2e/e2e_test.go
>  	now = time.Now()
I think that here we can unify the usage of `now` as we already did it above.

2022-12-15 14:48 UTC, svetlio8 commented on e2e/e2e_test.go
>  	now = time.Now()
I think that here we can unify the usage of `now` as we already did it above.

2022-12-15 14:50 UTC, svetlio8 commented on e2e/e2e_test.go
>  	signaturesStartTime := time.Now().UnixNano()
I think that we can remove this part and use the `now` in `verify.TopicMessagesWithStartTime` as we are doing above.

2022-12-15 14:51 UTC, svetlio8 commented on e2e/e2e_test.go
>  	now = time.Now()
I think that here we can unify the usage of `now` as we already did it above.

2022-12-15 14:58 UTC, svetlio8 commented on e2e/helper/submit/hedera.go
> +func NFTWithFeeToBridgeAccount(hederaClient *hedera.Client, bridgeAccount hedera.AccountID, memo string, token string, serialNum int64, fee int64) (*hedera.TransactionResponse, error) {
I think that we can remove the `chainId` - we already have the `memo`

2022-12-15 15:48 UTC, svetlio8 commented on e2e/e2e_test.go
> -	time.Sleep(20 * time.Second)
I think we will need a more stable fix, as we already sync we could have a re-try in case of timeout.

2022-12-15 15:54 UTC, svetlio8 commented on e2e/e2e_test.go
> -	time.Sleep(20 * time.Second)
I think we will need a more stable fix, as we already sync we could have a re-try in case of timeout.

2022-12-15 16:05 UTC, svetlio8 commented on e2e/helper/verify/evm.go
> +		//wrappedAsset := log.Topics[2]
Do we need to keep these comments?

2022-12-15 16:05 UTC, svetlio8 commented on e2e/helper/verify/evm.go
> +		//}
Do we need to keep these comments?

2022-12-15 16:05 UTC, svetlio8 commented on e2e/helper/verify/evm.go
> +		//}
Do we need to keep these comments?

2022-12-15 16:08 UTC, svetlio8 commented on e2e/helper/verify/hedera.go
> +func ScheduledMintTx(t *testing.T, hederaClient *hedera.Client, mirrorNodeClient *mirror_node.Client, account hedera.AccountID, asset string, expectedTransfers []transaction.Transfer, now time.Time)
I think that we can remove `hederaClient` - currently we are not using it in this funciton

2022-12-15 16:09 UTC, svetlio8 commented on e2e/helper/verify/hedera.go
> +func ScheduledBurnTx(t *testing.T, hederaClient *hedera.Client, mirrorNodeClient *mirror_node.Client, account hedera.AccountID, asset string, expectedTransfers []transaction.Transfer, now time.Time)
I think that we can remove hederaClient - currently, we are not using it in this function

2022-12-15 16:10 UTC, svetlio8 commented on e2e/helper/verify/hedera.go
> +func ScheduledNftAllowanceApprove(t *testing.T, hederaClient *hedera.Client, mirrorNodeClient *mirror_node.Client, bridgeAccount hedera.AccountID, payerAccount hedera.AccountID, expectedTransactionID
I think that we can remove `bridgeAccount` - currently, we are not using it in this function

2022-12-16 13:43 UTC, svetlio8 commented on e2e/setup/evm/setup.go
> +func WrappedToNativeAsset(assetsService service.Assets, sourceChainId uint64, asset string) (*asset.NativeAsset, error) {
Looks like this function isn't used anywhere. I think we can remove it.

2022-12-16 13:45 UTC, svetlio8 commented on e2e/setup/evm/setup.go
> +func RouterAndEVMTokenClientsFromEVMUtils(evmUtils map[uint64]Utils) (
Looks like this function isn't used anywhere. I think we can remove it or we can use it but to remove it from `e2e/setup/config.go`?

2022-12-16 13:49 UTC, svetlio8 commented on e2e/setup/config.go
> +func routerAndEVMTokenClientsFromEVMUtils(evmUtils map[uint64]evmSetup.Utils) (
Could you please pick one of the two `RouterAndEVMTokenClientsFromEVMUtils` between `e2e/setup/config.go` and  `e2e/setup/evm/setup.go`?

2022-12-16 13:53 UTC, svetlio8 commented on e2e/helper/submit/evm.go
> +		//WrappedAsset: *wrappedAsset,
Do we need to keep these comments?

2022-12-16 13:57 UTC, svetlio8 requested changes
please check the comments

2022-12-19 12:28 UTC, svetlio8 commented on e2e/e2e_test.go
> +// )
I think that we can remove these comments.

2022-12-19 12:48 UTC, svetlio8 commented on e2e/helper/verify/api.go
> +
I think that we can remove these comments.

2022-12-19 12:48 UTC, svetlio8 commented on e2e/helper/verify/api.go
> +
I think that we can remove these comments.

2022-12-20 13:12 UTC, svetlio8 approved these changes

2022-12-20 13:20 UTC, merged